go: &go
  image: golang
  working_dir: /go/src/github.com/gineshkumar/go-dbmigrate
  volumes:
    - $GOPATH:/go
go-test:
  <<: *go
  command: sh -c 'go get -t -v ./... && go test -p 1 -v ./...'
  links:
    - postgres
    - mysql
    - cassandra
    - mongo
go-build:
  <<: *go
  command: sh -c 'go get -v && go build -ldflags ''-s'' -o migrater'
  environment:
    CGO_ENABLED: 1
postgres:
  image: releases-docker.jfrog.io/jfrog/xray-postgres:9.5.2
mysql:
  image: mysql
  environment:
    MYSQL_DATABASE: migratetest
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
cassandra:
  image: cassandra:2.2
mongo:
  image: mongo:3.2.6
